image:
  repository: "ghcr.io/reillyse/hatchet-load-test/emitter"
  tag: "main"
  pullPolicy: "Always"

commandline:
  args: []
 
retainFailedHooks: false

env: {}

files: {}

restartPolicy: Always

deployment:
  annotations:
    app.kubernetes.io/name: workers
  labels: {}

ingress:
  enabled: false
  labels: {}
  annotations: {}
  hosts:
  tls:
  pathType: ImplementationSpecific

persistence:
  size: 5Gi

service:
  type: ClusterIP
  externalPort: 8081
  internalPort: 80

  externalIPs:
  #
  #
  ## LoadBalancer IP if service.type is LoadBalancer
  # loadBalancerIP: 10.2.2.2
  annotations: {}
  labels: {}
  ## Limit load balancer source ips to list of CIDRs (where available)
  # loadBalancerSourceRanges: []
  selector: {}
  # portName: service-port

serviceAccount:
  # Specifies whether a service account should be created
  create: true

extraContainers: []

extraVolumeMounts: []

extraVolumes: []

resources:
  limits:
    memory: 1024Mi
  requests:
    cpu: 250m
    memory: 1024Mi

priorityClassName: ""

# Affinity for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
# affinity: {}

# Tolerations for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

# Node labels for pod assignment
# Ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

# Common annotations for all pods
podAnnotations: {}

# Increasing replica count will deploy a separate pod for backend and jobs
# Example: with 3 replicas, you will end up with 3 backends + 1 jobs pod
replicaCount: 1
revisionHistoryLimit: 1

# podDisruptionBudget:
#   maxUnavailable: 1

# default security context
securityContext:
  enabled: false
  allowPrivilegeEscalation: false
  runAsUser: 1000
  fsGroup: 2000

extraConfigMapMounts: []

initContainers: []

extraManifests: []

# Support for AWS Security groups for pods
# Ref: https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html
securityGroupPolicy:
  enabled: false
  groupIds: []
