    engine:
      setupJob:
        enabled: true
        env:
          DATABASE_POSTGRES_PASSWORD: PASS
          DATABASE_URL: URL
      env:
        DATABASE_POSTGRES_PASSWORD: PASS
        DATABASE_URL: URL
        DATABASE_MAX_CONNS: "800"
      image:
        repository: "ghcr.io/hatchet-dev/hatchet/hatchet-api"
        tag: "v0.51.2"
        pullPolicy: "Always"      
    workers:
      replicaCount: 4            
    api:
      image:
        repository: "ghcr.io/hatchet-dev/hatchet/hatchet-api"
        tag: "v0.51.2"
        pullPolicy: "Always"
      env:
        DATABASE_POSTGRES_PASSWORD: PASS
        DATABASE_URL: URL
      envFrom:
        - secretRef:
            name: secret-name
      deploymentEnvFrom:
        - secretRef:
            name: secret-name            
    extraManifests:
    - apiVersion: rabbitmq.com/v1beta1
      kind: RabbitmqCluster
      metadata:
        name: rabbitmq
      spec:
        replicas: 1
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 800m
            memory: 1Gi