apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cloudflare-dns
spec:
  acme:
    email: alexander@hatchet.run
    privateKeySecretRef:
      name: letsencrypt-cloudflare-dns
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              namespace: cert-manager
              name: cloudflare-api-token-secret
              key: api-token
