apiVersion: v2
name: hatchet-stack
description: A Helm chart for deploying Hatchet on Kubernetes together with a PostgreSQL database and RabbitMQ.
type: application
version: 0.6.7
maintainers:
  - name: Hatchet Engineering
    email: alexander@hatchet.run
dependencies:
  - name: "hatchet-api"
    condition: api.enabled
    repository: "file://../hatchet-api"
    version: "^0.6.8"
    alias: api
  - name: "hatchet-api"
    condition: engine.enabled
    repository: "file://../hatchet-api"
    version: "^0.6.8"
    alias: engine
  - name: "hatchet-frontend"
    condition: frontend.enabled
    repository: "file://../hatchet-frontend"
    version: "^0.6.8"
    alias: frontend
  - name: "rabbitmq"
    condition: rabbitmq.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "^12.13.1"
    alias: rabbitmq
  - name: "workers"
    condition: workers.enabled
    repository: "file://../hatchet-workers"
    version: "^0.6.8"
    alias: workers
