version: "3"

tasks:
  gcp-login:
    cmds:
      - gcloud auth application-default login
    silent: true
  gen-benchmarks:
    cmds:
      - gcloud container clusters get-credentials benchmarks-cluster --region us-west1 --project hatchet-benchmarks
  use-benchmarks:
    cmds:
      - kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.5.5/cert-manager.crds.yaml
      - kubectl get crd clusterissuers.cert-manager.io
      - kubectl config use-context gke_hatchet-benchmarks_us-west1_benchmarks-cluster

